image: mcr.microsoft.com/dotnet/sdk:5.0

pipelines:
  default:
      - step:
          name: Build and Test
          caches:
            - dotnetcore
          script:
            - dotnet restore
            - dotnet build ${SOLUTION_NAME} --no-restore --configuration Release
            - dotnet publish --configuration Release --no-build ./src/${WEB_PROJECT_NAME}.csproj -o ./publish
          artifacts:
            - ./publish/**